name: Build PR

on:
  pull_request:
    branches: [ "main", "development" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: "Atom.sln"

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: [windows-latest]
    strategy:
      fail-fast: false
      matrix:
        build-configuration: [Debug, Release]
        system: [windows]
        architecture: [x86_64]

    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'VictorKrogh-Studios/Atom'
        submodules: recursive
        lfs: true

    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1.0.0
      with:
        vulkan_version: 1.3.296.0
        optional_components: com.lunarg.vulkan.debug
        install_runtime: false
        cache: false
        stripdown: true

    - name: Setup
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: ./Generate-Win.bat

    - uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Build
      run: MSBuild ${{env.SOLUTION_FILE_PATH}} /m /p:Configuration=${{matrix.build-configuration}} -fl -flp:logfile=logs/Build-${{matrix.build-configuration}}.log
